create schema if not exists app;

create table if not exists app.administradores (
    id integer generated by default as identity primary key,
    activo boolean not null,
    telefono varchar(30),
    contrasena varchar(72) not null,
    apellido varchar(100) not null,
    nombre varchar(100) not null,
    correo varchar(120) not null unique
);

create table if not exists app.clientes (
    id integer generated by default as identity primary key,
    activo boolean not null,
    telefono varchar(30),
    contrasena varchar(72) not null,
    apellido varchar(100) not null,
    nombre varchar(100) not null,
    correo varchar(120) not null unique
);

create table if not exists app.estudiantes (
    id integer generated by default as identity primary key,
    cliente_id integer not null unique,
    semestre integer not null constraint ck_estudiantes_semestre check (semestre between 1 and 20),
    codigo_estudiantil varchar(30) not null unique,
    programa_academico varchar(150) not null,
    universidad varchar(150) not null,
    constraint fk_estudiantes_cliente
        foreign key (cliente_id) references app.clientes (id)
);

create table if not exists app.tutores (
    id integer generated by default as identity primary key,
    cliente_id integer not null unique,
    disponible boolean not null,
    tarifa_por_hora numeric(12, 2) not null constraint ck_tutores_tarifa_positiva
        check (tarifa_por_hora > 0),
    calificacion_promedio double precision constraint ck_tutores_calificacion
        check (calificacion_promedio between 0 and 5),
    biografia varchar(2000),
    constraint fk_tutores_cliente
        foreign key (cliente_id) references app.clientes (id)
);

create table if not exists app.tutor_materias (
    tutor_id integer not null,
    orden integer not null check (orden >= 0),
    materia varchar(100) not null,
    primary key (orden, tutor_id),
    constraint fk_tutor_materias_tutor
        foreign key (tutor_id) references app.tutores (id)
);

create table if not exists app.reservas (
    id integer generated by default as identity primary key,
    costo_total numeric(12, 2) not null constraint ck_reservas_costo_positivo
        check (costo_total > 0),
    duracion_minutos integer not null constraint ck_reservas_duracion_positiva
        check (duracion_minutos > 0),
    estudiante_id integer not null,
    tutor_id integer not null,
    fecha date not null,
    hora_inicio time(0) without time zone not null,
    estado varchar(30) not null constraint ck_reservas_estado check (
        estado in ('PENDIENTE', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA')
    ),
    tema varchar(300) not null,
    constraint fk_reservas_estudiante
        foreign key (estudiante_id) references app.estudiantes (id),
    constraint fk_reservas_tutor
        foreign key (tutor_id) references app.tutores (id)
);

create unique index if not exists ux_clientes_correo_lower on app.clientes (lower(correo));
create unique index if not exists ux_administradores_correo_lower on app.administradores (lower(correo));

create index if not exists ix_estudiantes_cliente_id on app.estudiantes (cliente_id);
create index if not exists ix_tutores_cliente_id on app.tutores (cliente_id);
create index if not exists ix_reservas_estudiante_id on app.reservas (estudiante_id);
create index if not exists ix_reservas_tutor_id on app.reservas (tutor_id);

-- JDBC connects as the database owner, while Data API clients remain blocked by default.
alter table app.administradores enable row level security;
alter table app.clientes enable row level security;
alter table app.estudiantes enable row level security;
alter table app.tutores enable row level security;
alter table app.tutor_materias enable row level security;
alter table app.reservas enable row level security;
