create table app.conversaciones (
    id integer generated by default as identity primary key,
    reserva_id integer not null unique,
    estado varchar(20) not null default 'ACTIVA'
        constraint ck_conversaciones_estado check (estado in ('ACTIVA', 'CERRADA')),
    fecha_creacion timestamp not null default current_timestamp,
    version bigint not null default 0,
    constraint fk_conversacion_reserva foreign key (reserva_id) references app.reservas (id)
);

create table app.mensajes (
    id bigint generated by default as identity primary key,
    conversacion_id integer not null,
    remitente_usuario_id integer not null,
    contenido varchar(4000) not null,
    fecha_envio timestamp not null default current_timestamp,
    fecha_edicion timestamp,
    fecha_eliminacion timestamp,
    leido_en timestamp,
    version bigint not null default 0,
    constraint ck_mensajes_contenido check (length(trim(contenido)) between 1 and 4000),
    constraint fk_mensaje_conversacion foreign key (conversacion_id)
        references app.conversaciones (id),
    constraint fk_mensaje_remitente foreign key (remitente_usuario_id)
        references app.usuarios (id)
);

create index ix_mensajes_conversacion_fecha
    on app.mensajes (conversacion_id, fecha_envio, id);
create index ix_mensajes_remitente on app.mensajes (remitente_usuario_id);

alter table app.conversaciones enable row level security;
alter table app.mensajes enable row level security;
