-- Unifica la identidad, completa las entidades del dominio y conserva los datos existentes.
alter table app.clientes rename to usuarios;
alter table app.usuarios add column fecha_creacion timestamp not null default current_timestamp;
alter table app.usuarios add column fecha_actualizacion timestamp not null default current_timestamp;
alter table app.usuarios add column version bigint not null default 0;

create table app.usuario_roles (
    usuario_id integer not null,
    rol varchar(30) not null check (rol in ('ESTUDIANTE', 'TUTOR', 'ADMINISTRADOR')),
    primary key (usuario_id, rol),
    constraint fk_usuario_roles_usuario foreign key (usuario_id) references app.usuarios (id)
);

alter table app.estudiantes rename column cliente_id to usuario_id;
alter table app.tutores rename column cliente_id to usuario_id;
alter table app.tutores drop column calificacion_promedio;

insert into app.usuario_roles (usuario_id, rol)
select usuario_id, 'ESTUDIANTE' from app.estudiantes;
insert into app.usuario_roles (usuario_id, rol)
select usuario_id, 'TUTOR' from app.tutores
on conflict do nothing;

insert into app.usuarios (nombre, apellido, correo, contrasena, telefono, activo)
select nombre, apellido, correo, contrasena, telefono, activo
from app.administradores administrador
where not exists (
    select 1 from app.usuarios usuario where lower(usuario.correo) = lower(administrador.correo)
);
insert into app.usuario_roles (usuario_id, rol)
select usuario.id, 'ADMINISTRADOR'
from app.usuarios usuario
join app.administradores administrador on lower(administrador.correo) = lower(usuario.correo)
on conflict do nothing;
insert into app.usuario_roles (usuario_id, rol)
select usuario.id, 'ESTUDIANTE'
from app.usuarios usuario
where not exists (select 1 from app.usuario_roles rol where rol.usuario_id = usuario.id);
drop table app.administradores;

drop index if exists app.ux_clientes_correo_lower;
create unique index ux_usuarios_correo_lower on app.usuarios (lower(correo));
drop index if exists app.ix_estudiantes_cliente_id;
drop index if exists app.ix_tutores_cliente_id;
create index ix_estudiantes_usuario_id on app.estudiantes (usuario_id);
create index ix_tutores_usuario_id on app.tutores (usuario_id);

alter table app.estudiantes drop constraint if exists estudiantes_codigo_estudiantil_key;
alter table app.estudiantes drop constraint if exists ck_estudiantes_semestre;
alter table app.estudiantes add constraint ck_estudiantes_semestre check (semestre between 1 and 30);
alter table app.estudiantes add constraint ux_estudiante_institucion_codigo
    unique (universidad, codigo_estudiantil);

alter table app.tutor_materias rename to tutor_materias_legacy;
alter table app.tutor_materias_legacy drop constraint tutor_materias_pkey;
alter table app.tutor_materias_legacy drop constraint fk_tutor_materias_tutor;
create table app.materias (
    id integer generated by default as identity primary key,
    nombre varchar(100) not null unique
);
insert into app.materias (nombre)
select distinct trim(materia) from app.tutor_materias_legacy;
insert into app.materias (nombre) values ('Sin especificar') on conflict do nothing;
create table app.tutor_materias (
    tutor_id integer not null,
    materia_id integer not null,
    primary key (tutor_id, materia_id),
    constraint fk_tutor_materias_tutor foreign key (tutor_id) references app.tutores (id),
    constraint fk_tutor_materias_materia foreign key (materia_id) references app.materias (id)
);
insert into app.tutor_materias (tutor_id, materia_id)
select legacy.tutor_id, materia.id
from app.tutor_materias_legacy legacy
join app.materias materia on materia.nombre = trim(legacy.materia)
on conflict do nothing;
drop table app.tutor_materias_legacy;

alter table app.reservas add column materia_id integer;
update app.reservas set materia_id = (select id from app.materias where nombre = 'Sin especificar');
alter table app.reservas alter column materia_id set not null;
alter table app.reservas add constraint fk_reservas_materia
    foreign key (materia_id) references app.materias (id);
alter table app.reservas add column modalidad varchar(20) not null default 'VIRTUAL'
    check (modalidad in ('VIRTUAL', 'PRESENCIAL'));
alter table app.reservas add column ubicacion_o_enlace varchar(500);
alter table app.reservas add column moneda varchar(3) not null default 'COP';
alter table app.reservas add column motivo_cancelacion varchar(500);
alter table app.reservas add column fecha_cancelacion timestamp;
alter table app.reservas add column fecha_creacion timestamp not null default current_timestamp;
alter table app.reservas add column fecha_actualizacion timestamp not null default current_timestamp;
alter table app.reservas add column version bigint not null default 0;
alter table app.reservas drop constraint if exists ck_reservas_estado;
alter table app.reservas add constraint ck_reservas_estado check (
    estado in ('PENDIENTE', 'CONFIRMADA', 'RECHAZADA', 'EN_CURSO', 'COMPLETADA', 'CANCELADA')
);
create index ix_reservas_materia_id on app.reservas (materia_id);

create table if not exists app.disponibilidades_tutor (
    id integer generated by default as identity primary key,
    tutor_id integer not null,
    dia_semana varchar(15) not null check (dia_semana in (
        'LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO')),
    hora_inicio time(0) without time zone not null,
    hora_fin time(0) without time zone not null,
    constraint ck_disponibilidad_horas check (hora_fin > hora_inicio),
    constraint fk_disponibilidad_tutor foreign key (tutor_id) references app.tutores (id),
    constraint ux_disponibilidad_tutor_horario unique (tutor_id, dia_semana, hora_inicio, hora_fin)
);

create table if not exists app.resenas (
    id integer generated by default as identity primary key,
    reserva_id integer not null unique,
    calificacion integer not null check (calificacion between 1 and 5),
    comentario varchar(1000),
    fecha_creacion timestamp not null,
    constraint fk_resena_reserva foreign key (reserva_id) references app.reservas (id)
);

-- Older development databases created these tables through Hibernate before this migration.
-- Keep their rows, but remove duplicated participants: the reservation is authoritative.
do $$
begin
    if exists (select 1 from information_schema.columns
            where table_schema = 'app' and table_name = 'resenas' and column_name = 'estudiante_id') then
        if exists (select 1 from app.resenas review join app.reservas booking on booking.id = review.reserva_id
                where review.estudiante_id <> booking.estudiante_id or review.tutor_id <> booking.tutor_id) then
            raise exception 'Review participants disagree with their reservation; reconcile before migrating';
        end if;
        alter table app.resenas drop column estudiante_id;
        alter table app.resenas drop column tutor_id;
    end if;
    if not exists (select 1 from pg_constraint
            where conrelid = 'app.disponibilidades_tutor'::regclass and conname = 'ck_disponibilidad_horas') then
        alter table app.disponibilidades_tutor add constraint ck_disponibilidad_horas
            check (hora_fin > hora_inicio);
    end if;
    if not exists (select 1 from pg_constraint
            where conrelid = 'app.disponibilidades_tutor'::regclass
                and conname = 'ux_disponibilidad_tutor_horario') then
        alter table app.disponibilidades_tutor add constraint ux_disponibilidad_tutor_horario
            unique (tutor_id, dia_semana, hora_inicio, hora_fin);
    end if;
end;
$$;
alter table app.resenas alter column comentario drop not null;
alter table app.resenas alter column comentario type varchar(1000);
alter table app.disponibilidades_tutor alter column dia_semana type varchar(15);

create table app.bloqueos_agenda (
    id integer generated by default as identity primary key,
    tutor_id integer not null,
    fecha date not null,
    hora_inicio time(0) without time zone not null,
    hora_fin time(0) without time zone not null,
    motivo varchar(300),
    constraint ck_bloqueo_horas check (hora_fin > hora_inicio),
    constraint fk_bloqueo_tutor foreign key (tutor_id) references app.tutores (id)
);

create index ix_usuario_roles_rol on app.usuario_roles (rol);
create index ix_disponibilidades_tutor_id on app.disponibilidades_tutor (tutor_id);
create index ix_bloqueos_tutor_fecha on app.bloqueos_agenda (tutor_id, fecha);
alter table app.usuarios enable row level security;
alter table app.usuario_roles enable row level security;
alter table app.materias enable row level security;
alter table app.tutor_materias enable row level security;
alter table app.disponibilidades_tutor enable row level security;
alter table app.resenas enable row level security;
alter table app.bloqueos_agenda enable row level security;
