create schema if not exists app;

create table if not exists app.administradores (
    id integer generated by default as identity primary key,
    activo boolean not null,
    telefono varchar(30),
    contrasena varchar(72) not null,
    apellido varchar(100) not null,
    nombre varchar(100) not null,
    correo varchar(120) not null unique
);

create table if not exists app.clientes (
    id integer generated by default as identity primary key,
    activo boolean not null,
    telefono varchar(30),
    contrasena varchar(72) not null,
    apellido varchar(100) not null,
    nombre varchar(100) not null,
    correo varchar(120) not null unique
);

create table if not exists app.estudiantes (
    id integer generated by default as identity primary key,
    cliente_id integer not null unique,
    semestre integer not null,
    codigo_estudiantil varchar(30) not null unique,
    programa_academico varchar(150) not null,
    universidad varchar(150) not null,
    constraint fk_estudiantes_cliente
        foreign key (cliente_id) references app.clientes (id)
);

create table if not exists app.tutores (
    id integer generated by default as identity primary key,
    cliente_id integer not null unique,
    disponible boolean not null,
    tarifa_por_hora numeric(12, 2) not null,
    calificacion_promedio double precision,
    biografia varchar(2000),
    constraint fk_tutores_cliente
        foreign key (cliente_id) references app.clientes (id)
);

create table if not exists app.tutor_materias (
    tutor_id integer not null,
    orden integer not null check (orden >= 0),
    materia varchar(100) not null,
    primary key (orden, tutor_id),
    constraint fk_tutor_materias_tutor
        foreign key (tutor_id) references app.tutores (id)
);

create table if not exists app.reservas (
    id integer generated by default as identity primary key,
    costo_total numeric(12, 2) not null,
    duracion_minutos integer not null,
    estudiante_id integer not null,
    tutor_id integer not null,
    fecha date not null,
    hora_inicio time(0) without time zone not null,
    estado varchar(30) not null,
    tema varchar(300) not null,
    constraint fk_reservas_estudiante
        foreign key (estudiante_id) references app.estudiantes (id),
    constraint fk_reservas_tutor
        foreign key (tutor_id) references app.tutores (id)
);

-- JDBC connects as the database owner, while Data API clients remain blocked by default.
alter table app.administradores enable row level security;
alter table app.clientes enable row level security;
alter table app.estudiantes enable row level security;
alter table app.tutores enable row level security;
alter table app.tutor_materias enable row level security;
alter table app.reservas enable row level security;
